version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672" # RabbitMQ management UI
      - "5672:5672"   # RabbitMQ message port
    networks:
      - msnet

  user-service:
    build: ./user-service
    environment:
      - PORT=3004
    ports:
      - "3004:3004"
    networks:
      - msnet

  inventory-service:
    build: ./inventory-service
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - msnet

  order-service:
    build: ./order-service
    environment:
      - PORT=3003
      - RABBIT_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
      - inventory-service
    ports:
      - "3003:3003"
    networks:
      - msnet

  notification-service:
    build: ./notification-service
    environment:
      - PORT=3002
      - RABBIT_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    ports:
      - "3002:3002"
    networks:
      - msnet

  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000
    ports:
      - "3005:3000"
    networks:
      - msnet

  api-gateway:
    build: ./api-gateway
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - order-service
      - inventory-service
      - notification-service
    networks:
      - msnet

networks:
  msnet:
    driver: bridge